# Generated by Django 4.2.6 on 2023-11-16 16:48

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_consola_periferico_rename_anio_juego_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='juego',
            name='descripcion',
            field=ckeditor.fields.RichTextField(default='<p>Sin descripción</p>'),
            preserve_default=False,
        ),
    ]
