# Generated by Django 4.2.6 on 2023-11-16 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_juego_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='juego',
            name='fecha_lanzamiento',
            field=models.DateField(default='2023-11-16'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='juego',
            name='portada',
            field=models.ImageField(blank=True, null=True, upload_to='juego_portadas/'),
        ),
    ]
